@baseUrl =http://localhost:3050
@contentType =application/json


# @name registrer
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "Luis",
    "password": "Lasv12795*"
}

###

# @name login
POST {{baseUrl}}/auth/signin HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "Luis",
    "password": "Lasv12795*"
}

###

@authToken =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1aXMiLCJpYXQiOjE2MjQzNzA4MjQsImV4cCI6MTYyNDM3NDQyNH0.IsmGXIsRlziy7_E0F2R--KvDnJCkJXSvvro7zvW-3u4

# @name tasks/add
POST  {{baseUrl}}/tasks HTTP/1.1
Authorization: {{authToken}}
Content-Type: {{contentType}}

{
    "title": "Hacer deploy",
    "description": "desplegar"
}

###

# @name tasks/update
PATCH  {{baseUrl}}/tasks/e596f71f-1abd-4f42-8c26-6259adea4380/status HTTP/1.1
Authorization: {{authToken}}
Content-Type: {{contentType}}

{
    "status": "IN_PROGRESS"
}

###

# @name tasks/search
GET {{baseUrl}}/tasks?status=OPEN&search= HTTP/1.1
Authorization: {{authToken}}

###


# @name tasks/get/all
GET {{baseUrl}}/tasks HTTP/1.1
Authorization: {{authToken}}

###

# @name tasks/getById
GET {{baseUrl}}/tasks/e596f71f-1abd-4f42-8c26-6259adea4380 HTTP/1.1
Authorization: {{authToken}}

###

# @name tasks/update
DELETE   {{baseUrl}}/tasks/50317060-bee1-4f56-a902-c2c3c07c1ad5 HTTP/1.1
Authorization: {{authToken}}

###